#include "config_store.h"
#include "hardware/flash.h"
#include "hardware/sync.h"
#include "pico/flash.h"
#include "storage_layout.h"
#include <stddef.h>
#include <string.h>
#define SLOT_SIZE FLASH_SECTOR_SIZE
#define STORE_OFFSET (DISPENSER_BTSTACK_OFFSET-(2u*SLOT_SIZE))
static uint32_t crc32(const void *data,size_t len){uint32_t c=0xffffffffu;const uint8_t*p=data;while(len--){c^=*p++;for(int i=0;i<8;i++)c=(c>>1)^(0xedb88320u&-(int32_t)(c&1));}return~c;}
typedef struct{uint32_t version,sequence;char wifi_ssid[33],wifi_password[65];float screw_pitch_mm;uint16_t motor_steps_per_rev,microsteps;float manual_speed_mm_s,dosing_speed_mm_s,acceleration_mm_s2;float retract_distance_mm,retract_speed_mm_s;uint32_t retract_delay_ms;float position_min_mm,position_max_mm;uint32_t manual_timeout_ms;int8_t stallguard_threshold;uint16_t stallguard_warning_level,stallguard_filter_count;uint16_t stallguard_critical_level,stallguard_baseline;float stallguard_calibration_speed_mm_s;uint8_t stallguard_enabled;uint32_t crc;}config_v2_t;
typedef struct{uint32_t version,sequence;char wifi_ssid[33],wifi_password[65];float screw_pitch_mm;uint16_t motor_steps_per_rev,microsteps;float manual_speed_mm_s,dosing_speed_mm_s,trigger_dose_mm,acceleration_mm_s2;float retract_distance_mm,retract_speed_mm_s;uint32_t retract_delay_ms;float position_min_mm,position_max_mm;uint32_t manual_timeout_ms;int8_t stallguard_threshold;uint16_t stallguard_warning_level,stallguard_filter_count;uint16_t stallguard_critical_level,stallguard_baseline;float stallguard_calibration_speed_mm_s;uint8_t stallguard_enabled;uint32_t crc;}config_v3_t;
void device_config_defaults(device_config_t*c){memset(c,0,sizeof(*c));c->version=DEVICE_CONFIG_VERSION;c->screw_pitch_mm=2;c->motor_steps_per_rev=200;c->microsteps=16;c->motor_run_current_mA=800;c->motor_hold_current_mA=300;c->manual_speed_mm_s=5;c->dosing_speed_mm_s=5;c->trigger_dose_mm=.8f;c->acceleration_mm_s2=100;c->retract_distance_mm=.1f;c->retract_speed_mm_s=3;c->retract_delay_ms=50;c->position_min_mm=0;c->position_max_mm=120;c->manual_timeout_ms=30000;c->stallguard_threshold=0;c->stallguard_filter_count=4;}
bool device_config_validate(const device_config_t*c){if(!c||c->version!=DEVICE_CONFIG_VERSION||!c->motor_steps_per_rev||c->screw_pitch_mm<=0||c->microsteps>256||!c->microsteps||(c->microsteps&(c->microsteps-1)))return false;if(c->stallguard_enabled&&(!c->stallguard_baseline||c->stallguard_critical_level>=c->stallguard_warning_level||c->stallguard_warning_level>=c->stallguard_baseline))return false;return c->motor_run_current_mA>=100&&c->motor_run_current_mA<=1900&&c->motor_hold_current_mA>=100&&c->motor_hold_current_mA<=c->motor_run_current_mA&&c->manual_speed_mm_s>0&&c->manual_speed_mm_s<=25&&c->dosing_speed_mm_s>0&&c->trigger_dose_mm>0&&c->trigger_dose_mm<=100&&c->acceleration_mm_s2>0&&c->position_max_mm>c->position_min_mm&&c->manual_timeout_ms>=100;}
static bool valid(const device_config_t*c){return device_config_validate(c)&&c->crc==crc32(c,offsetof(device_config_t,crc));}
static bool valid_v2(const config_v2_t*c){return c->version==2&&c->crc==crc32(c,offsetof(config_v2_t,crc));}
static bool valid_v3(const config_v3_t*c){return c->version==3&&c->crc==crc32(c,offsetof(config_v3_t,crc));}
static void migrate_common(device_config_t*out,const config_v3_t*old){device_config_defaults(out);out->sequence=old->sequence;memcpy(out->wifi_ssid,old->wifi_ssid,sizeof(out->wifi_ssid));memcpy(out->wifi_password,old->wifi_password,sizeof(out->wifi_password));out->screw_pitch_mm=old->screw_pitch_mm;out->motor_steps_per_rev=old->motor_steps_per_rev;out->microsteps=old->microsteps;out->manual_speed_mm_s=old->manual_speed_mm_s;out->dosing_speed_mm_s=old->dosing_speed_mm_s;out->trigger_dose_mm=old->trigger_dose_mm;out->acceleration_mm_s2=old->acceleration_mm_s2;out->retract_distance_mm=old->retract_distance_mm;out->retract_speed_mm_s=old->retract_speed_mm_s;out->retract_delay_ms=old->retract_delay_ms;out->position_min_mm=old->position_min_mm;out->position_max_mm=old->position_max_mm;out->manual_timeout_ms=old->manual_timeout_ms;out->stallguard_threshold=old->stallguard_threshold;out->stallguard_warning_level=old->stallguard_warning_level;out->stallguard_filter_count=old->stallguard_filter_count;out->stallguard_critical_level=old->stallguard_critical_level;out->stallguard_baseline=old->stallguard_baseline;out->stallguard_calibration_speed_mm_s=old->stallguard_calibration_speed_mm_s;out->stallguard_enabled=old->stallguard_enabled;}
bool config_store_load(device_config_t*out){const void*pa=(const void*)(XIP_BASE+STORE_OFFSET),*pb=(const void*)(XIP_BASE+STORE_OFFSET+SLOT_SIZE);const device_config_t*a=pa,*b=pb;bool va=valid(a),vb=valid(b);if(va||vb){*out=vb&&(!va||b->sequence>a->sequence)?*b:*a;return true;}const config_v3_t*a3=pa,*b3=pb;bool va3=valid_v3(a3),vb3=valid_v3(b3);if(va3||vb3){migrate_common(out,vb3&&(!va3||b3->sequence>a3->sequence)?b3:a3);return true;}const config_v2_t*a2=pa,*b2=pb;bool va2=valid_v2(a2),vb2=valid_v2(b2);if(va2||vb2){const config_v2_t*old=vb2&&(!va2||b2->sequence>a2->sequence)?b2:a2;config_v3_t bridge={0};bridge.sequence=old->sequence;memcpy(bridge.wifi_ssid,old->wifi_ssid,sizeof(bridge.wifi_ssid));memcpy(bridge.wifi_password,old->wifi_password,sizeof(bridge.wifi_password));bridge.screw_pitch_mm=old->screw_pitch_mm;bridge.motor_steps_per_rev=old->motor_steps_per_rev;bridge.microsteps=old->microsteps;bridge.manual_speed_mm_s=old->manual_speed_mm_s;bridge.dosing_speed_mm_s=old->dosing_speed_mm_s;bridge.trigger_dose_mm=.8f;bridge.acceleration_mm_s2=old->acceleration_mm_s2;bridge.retract_distance_mm=old->retract_distance_mm;bridge.retract_speed_mm_s=old->retract_speed_mm_s;bridge.retract_delay_ms=old->retract_delay_ms;bridge.position_min_mm=old->position_min_mm;bridge.position_max_mm=old->position_max_mm;bridge.manual_timeout_ms=old->manual_timeout_ms;bridge.stallguard_threshold=old->stallguard_threshold;bridge.stallguard_warning_level=old->stallguard_warning_level;bridge.stallguard_filter_count=old->stallguard_filter_count;bridge.stallguard_critical_level=old->stallguard_critical_level;bridge.stallguard_baseline=old->stallguard_baseline;bridge.stallguard_calibration_speed_mm_s=old->stallguard_calibration_speed_mm_s;bridge.stallguard_enabled=old->stallguard_enabled;migrate_common(out,&bridge);return true;}device_config_defaults(out);return false;}
typedef struct{uint32_t offset;uint8_t page[FLASH_PAGE_SIZE];} write_ctx_t;
static void do_write(void*p){write_ctx_t*w=p;flash_range_erase(w->offset,SLOT_SIZE);flash_range_program(w->offset,w->page,FLASH_PAGE_SIZE);}
bool config_store_save(device_config_t*c){if(!device_config_validate(c)||sizeof(*c)>FLASH_PAGE_SIZE)return false;device_config_t old;config_store_load(&old);c->sequence=old.sequence+1;c->crc=crc32(c,offsetof(device_config_t,crc));write_ctx_t w={STORE_OFFSET+(c->sequence&1u)*SLOT_SIZE,{0xff}};memcpy(w.page,c,sizeof(*c));return flash_safe_execute(do_write,&w,1000)==PICO_OK;}
static void do_erase(void*p){(void)p;flash_range_erase(STORE_OFFSET,2u*SLOT_SIZE);}
bool config_store_factory_reset(void){return flash_safe_execute(do_erase,0,1000)==PICO_OK;}
